[package]
name = "ka3005p"
version = "0.1.2"
authors = ["Nicola Coretti <nico.coretti@gmail.com>"]
edition = "2018"
autobins = false
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "cli tool to remote control a ka3005p power supply"
homepage = "https://github.com/Nicoretti/ka3005p"
repository = "https://github.com/Nicoretti/ka3005p"
keywords = ["power-supply", "remote-control", "serial", "ka3000", "ka3005p"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.0"
structopt = "0.3.15"
human-panic = "1.0.3"
anyhow = "1.0.31"

[[bin]]
name = "ka3005p"
path = "src/bin/ka3005p.rs"
